export const InputPresets = [
  {
    title: 'Small Input',
    width: '50px',
    height: '15px',
    value: '',
    disabled: false,
    size: 'medium',
  },
  {
    title: 'Medium Input',
    width: '100px',
    height: '20px',
    value: '',
    disabled: false,
    size: 'medium',
  },
  {
    title: 'Large Input',
    width: '200px',
    height: '40px',
    value: '',
    disabled: false,
    size: 'medium',
  },
  {
    title: 'Pre-filled Input',
    width: '100px',
    height: '20px',
    value: 'Hello, This is an input component.',
    disabled: false,
    size: 'medium',
  },
  {
    title: 'Pre-filled with disabled',
    value: 'Hello, This is an input component with disabled.',
    width: '100px',
    height: '20px',
    disabled: true,
    size: 'medium',
  },
  {
    title: 'Disabled input with large border radius',
    size: 'large',
    width: '100px',
    height: '20px',
    disabled: true,
    value: '',
  },
];
